#:schema node_modules/wrangler/config-schema.json
name = "faka-store"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[triggers]
crons = ["*/1 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "faka-db"
database_id = "750ddc20-8086-464f-bf71-d52e06ff2d86"

[[kv_namespaces]]
binding = "KV"
id = "40c2abbaa1984d57a9a3dc89d91cc3d9"

[vars]
# ===== 站点配置 =====
SITE_NAME = "樱花市集"
SITE_WELCOME = "欢迎来到二次元自助服务商店"
# ===== 确认数阈值 =====
TRON_CONFIRMATIONS = "19"
# 轮询间隔 (秒)
POLL_INTERVAL = "60"
# ===== TRON 链上 RPC =====
TRON_RPC_URL = "https://api.trongrid.io"
